# Generated by Django 4.1.1 on 2022-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('wallet_bal', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
