# Generated by Django 4.1.1 on 2022-10-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='forget_password_token',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
