# Generated by Django 4.1.1 on 2022-10-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identify_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['date_created']},
        ),
    ]
